# Generated by Django 3.2.3 on 2021-05-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='student',
            name='Attendance',
            field=models.DecimalField(decimal_places=2, default=99, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='className',
            field=models.CharField(default='math', help_text='Enter a student name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='sectionName',
            field=models.CharField(default='sectionA', help_text='Enter a student name', max_length=200),
            preserve_default=False,
        ),
    ]
