# Generated by Django 3.2.3 on 2021-05-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210524_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Attendance',
            new_name='attendance',
        ),
    ]
