# Generated by Django 3.2.3 on 2021-05-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_attendance_student_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.CharField(help_text='Enter a student name', max_length=200),
        ),
    ]
