# Generated by Django 3.2.3 on 2021-05-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_student_attendance2'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='className',
            field=models.CharField(default=100, help_text='Enter a student name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='sectionName',
            field=models.CharField(default=501, help_text='Enter a student name', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(help_text='Enter a student name', max_length=200),
        ),
    ]
