# Generated by Django 3.2.3 on 2021-05-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': ['class']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='Department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='shortname',
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(max_length=50, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.CharField(max_length=50, primary_key='True', serialize=False),
        ),
    ]
