# Generated by Django 3.2.3 on 2021-05-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20210525_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
    ]
