# Generated by Django 3.2.3 on 2021-05-25 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20210525_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter a dob ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, help_text='Enter a student phone no', max_length=200),
            preserve_default=False,
        ),
    ]
