# Generated by Django 3.2.3 on 2021-05-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20210525_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classEndDate',
            field=models.DateField(default='2021-08-10'),
        ),
        migrations.AddField(
            model_name='course',
            name='classStartDate',
            field=models.DateField(default='2021-05-18'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(max_length=50, primary_key=True, serialize=False)),
                ('totalAttendanceUptoToday', models.IntegerField(help_text='Enter a student attendance', max_length=200)),
                ('isPresent', models.BooleanField(default='True')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
    ]
