# Generated by Django 3.2.3 on 2021-05-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_attendance_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='campus',
        ),
        migrations.AddField(
            model_name='course',
            name='totalClassDay',
            field=models.IntegerField(default=30),
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
