# Generated by Django 3.2.3 on 2021-05-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20210525_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.IntegerField(max_length=50, primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(max_length=50, primary_key='True', serialize=False),
        ),
    ]
