# Generated by Django 3.2.3 on 2021-05-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20210526_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
