# Generated by Django 3.2.3 on 2021-05-26 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_attendance_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
