# Generated by Django 3.2.3 on 2021-05-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_alter_attendance_fordate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='forDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
